### ISSUE TITLE
以后版本考虑加入aqicn.org空气质量么？

### ISSUE THREAD

**Issue by wangbolizhong** [hocgin/WeatherForChrome#1]
Chrome Version: 61.0.3163.100 64bit
OS: windows7 64bit
=========

**Comment by hocgin** [comment]
@wangbolizhong 是PM值吗 ?

**Comment by wangbolizhong** [comment]
是的。当前版本看不出降水概率吧？

**Comment by hocgin** [comment]
嗯 只有近三小时的降水量.. 我最近找找有没有新 API 更新以下 : )

**Comment by wangbolizhong** [comment]
怎么还显示小数点后 ![image](https://user-images.githubusercontent.com/11750269/31334314-6abe84c8-ad20-11e7-8ca5-9cc10abb8dd5.png)

**Comment by hocgin** [comment]
@wangbolizhong [0.0.3](https://chrome.google.com/webstore/detail/weather/ibieofighcnndjcjchdahdiacjpmkhgf?hl=zh-CN&gl=001)
已进行了更新..
![0-0-3](https://user-images.githubusercontent.com/16535610/31335295-8801ea7a-acb7-11e7-882d-d5191d62ba6e.gif)
温度有4位数的是我没考虑到的@。@

**Comment by hocgin** [comment]
你是不是使用了 华氏度之类的..

**Comment by wangbolizhong** [comment]
要不要把特色功能支持空气质量写在“Chrome 天气预告插件”里？

**Comment by hocgin** [comment]
这句话是什么意思呢？
关于多位数的这个问题我现在解决, 但是想到 badge 只支持3个字符 很头痛

**Comment by hocgin** [comment]
哈哈 有道理🤠
