### ISSUE TITLE
chrome extension 网站版本过老

### ISSUE THREAD

**Issue by icesof** [hocgin/WeatherForChrome#3]
Chrome Version: 
OS: 
=========
https://chrome.google.com/webstore/detail/weather-for-chrome/bckebbpihkkoonigakijdplcakdgfdfg

依然是1.0.3，没有空气质量等信息，期待ing

**Comment by scavin** [comment]
你搞错了吧
https://chrome.google.com/webstore/detail/ibieofighcnndjcjchdahdiacjpmkhgf
