### ISSUE TITLE
链接被拒绝检查Api

### ISSUE THREAD

**Issue by BlingRabbit** [hocgin/WeatherForChrome#5]
Chrome Version: 62.0.3202.75
OS: Win10 
=========
![image](https://user-images.githubusercontent.com/10525250/32145861-278cb75c-bd0a-11e7-908c-0ad14b501dba.png)
我按照提示进行了api的申请与替换 为什么总是提示这个呢？连接被拒接 是因为我网络问题吗？

**Comment by hocgin** [comment]
@BlingRabbit 😉
- 有可能是忘记保存了。
- 或者可以使用下面的方式查看一下Token是否正常。
http://api.openweathermap.org/data/2.5/weather?q=xiamen,cn&appid=`your-token`

**Comment by BlingRabbit** [comment]
啊啊..还是不行啊
API确定没有问题 通过连接可以获取天气信息 可是 我的Chorme一直提示错误
不知道到底是哪里出错了...

**Comment by hocgin** [comment]
早上好，😋这个提示只有返回数据，出现异常才会出现。你也可以右键，悬浮框 查看更多的日志信息。

**Comment by BlingRabbit** [comment]
您好~
一直错误 不知道是哪里错了到底 
相反 在Opera上没有问题....是我使用绿色版Chrome的原因吗？
右键悬浮窗没有更多日志

感觉是我Chrome的问题...不知道怎么解决...

**Comment by hocgin** [comment]
@BlingRabbit 
不好意思, 好像描述出了点问题.. 囧。。不是右键悬浮框 
查看日志方法:
1. 更多工具 > 扩展程序 `开启开发者模式(右上角)`
2. 如图操作
![2017-11-07 05 57 11](https://user-images.githubusercontent.com/16535610/32466465-02b65c16-c382-11e7-85e3-603827c0ebd1.png)
3. 如图操作 `找到对应请求(openweathermap.org)查看 cod 字段，如红字部分!!`
<img width="835" alt="2017-11-07 05 58 29" src="https://user-images.githubusercontent.com/16535610/32466476-0ad666b6-c382-11e7-9be7-90b575b7f335.png">

**Comment by BlingRabbit** [comment]
哦哈 我知道什么问题了
我经度写了116 返回信息写着400：116不是浮点数...
然后我改了一下就可以了 好神奇 谢谢啦~

**Comment by hocgin** [comment]
😋
