### ISSUE TITLE
Firefox 支持

### ISSUE THREAD

**Issue by Rictusempra** [hocgin/WeatherForChrome#8]
Chrome Version: N/A
OS: Windows 10.16299.98 Pro
=========
从公有API来看似乎工作量很小？
https://developer.mozilla.org/Add-ons/WebExtensions

update: 直接修改后缀名强行安装并未发现严重问题

**Comment by Rictusempra** [comment]
官方测试工具初步报告为兼容 https://www.extensiontest.com/test/cd546780-f355-11e7-8d7e-453caf272a00

**Comment by hocgin** [comment]
@Rictusempra  不好意思 因为我平时都用 Chrome。感谢，我这就去下个 Firebox 看看 ☺️

**Comment by hocgin** [comment]
@Rictusempra 我已经尝试发布到`Firefox`了
- [Firefox 插件下载](https://addons.mozilla.org/zh-CN/firefox/addon/weather-for-firefox/) 因为比较匆忙，细节可能并没处理彻底，欢迎继续提交意见。☺️
- [相关移植代码](https://github.com/hocgin/WeatherForFirefox) 如果有兴趣的话😘。


好了，晚安
